### ISSUE TITLE
Istanbul Dependency?

### ISSUE THREAD

**Issue by UnknownTraveller** [daffl/uberproto#17]
Hello,

I noticed that after updating from 1.2, npm installed nearly 100 new packages. The new major release of uberproto seems to depend on `instanbul@1.1.0-alpha.1` (it's a real dependency, not a devDependency).

Is that really intended? This adds more than 10mb of files under node_modules that shouldn't be necessary for the library to run.

**Comment by daffl** [comment]
Wow, no idea what happened there. Thank you, fixed in v2.0.3
